name: monthly run

on:
  schedule:
    # ───── 18:00 UTC on the 14-th of every month ─────
    - cron: '0 18 14 * *'
  workflow_dispatch:      # lets me trigger it manually

permissions:
  contents: write
  issues: write

jobs:
  momentum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas yfinance numpy
          pip install markdown PyYAML

      - name: Run momentum screen
        run: python sector_momentum_screen.py

      - name: Generate HTML report
        run: |
          python -c "
          import pandas as pd
          from datetime import datetime, timedelta

          # --- Load and process data ---
          df = pd.read_csv('momentum_scores.csv')
          df.dropna(subset=['MomentumScore', 'Return12m'], inplace=True)
          df[['MomentumScore', 'Return12m']] = df[['MomentumScore', 'Return12m']].apply(pd.to_numeric, errors='coerce')
          bond_ticker = 'AGG'
          
          # --- Prepare content ---
          today = datetime.now()
          next_rebalance_date = (today.replace(day=1) + timedelta(days=32)).replace(day=14)
          top_5_winners = df.nlargest(5, 'MomentumScore')
          
          # --- Build HTML ---
          html_content = f'''
          <!DOCTYPE html>
          <html lang=\"en\">
          <head>
              <meta charset=\"UTF-8\">
              <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
              <title>Sector Momentum Report - {today.strftime('%Y-%m-%d')}</title>
              <style>
                  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; color: #333; }}
                  .container {{ max-width: 800px; margin: 40px auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }}
                  h1, h2, h3 {{ color: #111; }}
                  h1 {{ text-align: center; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 20px; }}
                  h2, h3 {{ border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 40px; }}
                  .timestamp {{ text-align: center; color: #666; font-size: 0.9em; margin-bottom: 30px; }}
                  .summary {{ background: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0; border: 1px solid #eee;}}
                  table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                  th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
                  th {{ background-color: #f8f9fa; font-weight: 600; }}
                  tr:hover {{ background-color: #f1f1f1; }}
                  .positive {{ color: #28a745; font-weight: bold; }}
                  .negative {{ color: #dc3545; font-weight: bold; }}
                  .checklist {{ list-style-type: none; padding-left: 0; }}
                  .checklist li {{ background: #f9f9f9; margin-bottom: 10px; padding: 15px; border-radius: 5px; border-left: 4px solid #007bff; }}
                  .checklist li strong {{ color: #0056b3; }}
                  footer {{ text-align: center; margin-top: 40px; padding-top: 20px; border-top: 2px solid #eee; font-size: 0.8em; color: #777; }}
              </style>
          </head>
          <body>
              <div class='container'>
                  <h1>📈 Sector Momentum Report</h1>
                  <div class='timestamp'>Generated on {today.strftime('%Y-%m-%d %H:%M UTC')}</div>

                  <div class='summary'>
                      <h3>📊 Summary</h3>
                      <p><strong>Total ETFs analyzed:</strong> {len(df)}</p>
                      <p><strong>Top performers:</strong> {len(df[df['MomentumScore'] > 0])} ETFs with positive momentum</p>
                  </div>

                  <h2>Trading Checklist (IBKR)</h2>
                  <ol class='checklist'>
                      <li><strong>Log in</strong> to IBKR → <em>Portfolio</em> tab.</li>
                      <li><strong>Exit</strong> any ETF <strong>not in the Top-3 Winners list</strong>.</li>
                      <li><strong>Enter</strong> each of the Top-3 winners so positions are equal-weighted (e.g., Target size ≈ <strong>€10,000</strong> each).</li>
                      <li><strong>Confirm fills</strong> in <em>Trades</em> panel.</li>
                  </ol>

                  <h2>Next Key Dates</h2>
                  <ul class='checklist'>
                      <li><strong>{next_rebalance_date.strftime('%Y-%m-%d')}</strong>: Next scheduled automated screen.</li>
                      <li><strong>Mid-month check</strong>: If a holding drops > 12%, consider swapping it into {bond_ticker}.</li>
                  </ul>

                  <h3>🏆 Top 5 Momentum Winners</h3>
                  <table>
                      <tr><th>Rank</th><th>Ticker</th><th>Momentum Score</th><th>12-Month Return</th></tr>
          '''

          for i, (idx, row) in enumerate(top_5_winners.iterrows(), 1):
              mom_class = 'positive' if row['MomentumScore'] > 0 else 'negative'
              ret_class = 'positive' if row['Return12m'] > 0 else 'negative'
              html_content += f'''
                      <tr>
                          <td>{i}</td>
                          <td><strong>{row['Ticker']}</strong></td>
                          <td class='{mom_class}'>{row['MomentumScore']*100:.2f}%</td>
                          <td class='{ret_class}'>{row['Return12m']*100:.2f}%</td>
                      </tr>
              '''
          
          html_content += '''
                  </table>
                  
                  <h3>📋 Complete Results</h3>
                  <table>
                      <tr><th>Ticker</th><th>Momentum Score</th><th>12-Month Return</th></tr>
          '''

          for idx, row in df.sort_values(by='MomentumScore', ascending=False).iterrows():
              mom_class = 'positive' if row['MomentumScore'] > 0 else 'negative'
              ret_class = 'positive' if row['Return12m'] > 0 else 'negative'
              html_content += f'''
                      <tr>
                          <td><strong>{row['Ticker']}</strong></td>
                          <td class='{mom_class}'>{row['MomentumScore']*100:.2f}%</td>
                          <td class='{ret_class}'>{row['Return12m']*100:.2f}%</td>
                      </tr>
              '''

          html_content += '''
                  </table>
                   <footer>
                      <p><em>Reminder: the model is mechanical; avoid discretionary overrides unless liquidity becomes an issue.</em></p>
                  </footer>
              </div>
          </body>
          </html>
          '''
          
          with open('momentum_report.html', 'w') as f:
              f.write(html_content)
          
          with open('index.html', 'w') as f:
              f.write(html_content)
          "

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add momentum_scores.csv momentum_report.html index.html
          git commit -m "Update momentum results - $(date +'%Y-%m-%d')" || exit 0
          git push origin main

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: momentum_scores
          path: momentum_scores.csv

      - name: Generate and send email report
        env:
          EMAIL_PASSWORD: ${{ secrets.Email }}
        run: python3 generate_email.py

      - name: Create notification issue
        if: failure()
        run: |
          echo "Workflow failed. Please check the logs for details."
      
      - name: Create GitHub issue notification
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Workflow failed: Momentum Report - ${new Date().toISOString().split('T')[0]}`,
              body: 'The monthly momentum workflow failed. Please check the logs for details.',
              labels: ['workflow-failure']
            }); 