name: monthly run

on:
  schedule:
    # ───── 18:00 UTC on the 14-th of every month ─────
    - cron: '0 18 14 * *'
  workflow_dispatch:      # lets me trigger it manually

permissions:
  contents: write
  issues: write

jobs:
  momentum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas yfinance numpy
          pip install markdown PyYAML

      - name: Run momentum screen
        run: python sector_momentum_screen.py

      - name: Generate data file
        run: python3 generate_data_json.py

      - name: Verify data integrity
        run: python3 refresh_data.py

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add momentum_scores.csv data.json index.html historical_momentum.json
          git commit -m "Update momentum results - $(date +'%Y-%m-%d')" || exit 0
          git push origin main

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: momentum_scores
          path: |
            momentum_scores.csv
            momentum_scores.json
            historical_momentum.json

      - name: Copy files to docs folder for GitHub Pages
        run: |
          mkdir -p docs
          cp data.json docs/
          cp index.html docs/
          cp historical_momentum.json docs/

      - name: Commit updated files to Pages path
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update GitHub Pages files"
          branch: main
          file_pattern: docs/

      - name: Generate and send email report
        env:
          EMAIL_PASSWORD: ${{ secrets.Email }}
        run: python3 generate_email.py

      - name: Create notification issue
        if: failure()
        run: |
          echo "Workflow failed. Please check the logs for details."
      
      - name: Create GitHub issue notification
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Workflow failed: Momentum Report - ${new Date().toISOString().split('T')[0]}`,
              body: 'The monthly momentum workflow failed. Please check the logs for details.',
              labels: ['workflow-failure']
            }); 